version: "3"
services:
    django:
        build: ./musicplayer8
        volumes:
            - ./musicplayer8:/usr/src/app
        ports:
            - 8000:8000
        environment:
            POSTGRES_USER: "django"
            POSTGRES_PASSWORD: "pass1234"
            POSTGRES_DB: "django_db"
    
    postgres:
        image: postgres:12.3
        environment:
            POSTGRES_USER: "django"
            POSTGRES_PASSWORD: "pass1234"
            POSTGRES_DB: "django_db"
        volumes:
            - musicplayer8db:/var/lib/postgresql/data/

volumes:
    musicplayer8db: